debug: false


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    hello:
      board: debug
    org.springframework.web.servlet: debug
    #JPA ???? ???
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: chan
    password: thisisTESTpw!#%&
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3.decoupled-logic: true
---
spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driverClassName: org.h2.Driver
  sql.init.mode: always
  jpa:
    defer-datasource-initialization: true
  test.database.replace: none